// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Labelid;
extern lv_obj_t * ui_Labelage;
extern lv_obj_t * ui_Labelname;
extern lv_obj_t * ui_Labelsex;
extern lv_obj_t * ui_Labeljudge;
extern lv_obj_t * ui_TabView4;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_TabPage2;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Container7update;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_TextArea4;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_TabPage3;
void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container7update1;
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Container7;
void ui_event_Switch5(lv_event_t * e);
extern lv_obj_t * ui_Switch5;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label17;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label15;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Spinbox5;
extern lv_obj_t * ui_TextArea5;
extern lv_obj_t * ui_Labelid1;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_TextArea6;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_backgroud4_png);    // assets/backgroud4.png
LV_IMG_DECLARE(ui_img_face_png);    // assets/face.png
LV_IMG_DECLARE(ui_img_backgroud3_png);    // assets/backgroud3.png
LV_IMG_DECLARE(ui_img_backgroud1_png);    // assets/backgroud1.png
LV_IMG_DECLARE(ui_img_backgroud2_png);    // assets/backgroud2.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png



LV_FONT_DECLARE(ui_font_Fontcn15);
LV_FONT_DECLARE(ui_font_Fontcn20);
LV_FONT_DECLARE(ui_font_Fontcn30);
LV_FONT_DECLARE(ui_font_Fontcnmsg);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
